// <auto-generated />
namespace EL.EntityModels.Contexts._GeneralMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class _23 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_23));
        
        string IMigrationMetadata.Id
        {
            get { return "201501051832011_23"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
