// <auto-generated />
namespace EL.EntityModels.Contexts._Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class test : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(test));
        
        string IMigrationMetadata.Id
        {
            get { return "201501072110025_test"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
