//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EL.Logic.WebApiCore.Resources {
    using System;

    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApiErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApiErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IM.Gfr.Server.Resources.ApiErrors", typeof(ApiErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access is denied, or a system error has occurred..
        /// </summary>
        public static string DefaultDocumentErrorMessage {
            get {
                return ResourceManager.GetString("DefaultDocumentErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to session is denied.
        /// </summary>
        public static string Error_AccessToSessionIsDenied {
            get {
                return ResourceManager.GetString("Error_AccessToSessionIsDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Error.
        /// </summary>
        public static string Error_Internal_Error {
            get {
                return ResourceManager.GetString("Error_Internal_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unspecified error.
        /// </summary>
        public static string Error_Internal_UnspecifiedError {
            get {
                return ResourceManager.GetString("Error_Internal_UnspecifiedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid XML.
        /// </summary>
        public static string Error_Invalid_Xml {
            get {
                return ResourceManager.GetString("Error_Invalid_Xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid argument: {0}.
        /// </summary>
        public static string Error_InvalidArgument {
            get {
                return ResourceManager.GetString("Error_InvalidArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to document denied..
        /// </summary>
        public static string Error_OpenDocument_AccessDenied {
            get {
                return ResourceManager.GetString("Error_OpenDocument_AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to document source can&apos;t be established or document absent.
        /// </summary>
        public static string Error_OpenDocument_Document_CantFindOrConnect {
            get {
                return ResourceManager.GetString("Error_OpenDocument_Document_CantFindOrConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document accessing failed due to server low disk space.
        /// </summary>
        public static string Error_OpenDocument_NoDiskSpace {
            get {
                return ResourceManager.GetString("Error_OpenDocument_NoDiskSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document doesn&apos;t contains data of requested kind.
        /// </summary>
        public static string Error_OpenDocument_NoSuchDataKind {
            get {
                return ResourceManager.GetString("Error_OpenDocument_NoSuchDataKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document not available.
        /// </summary>
        public static string Error_OpenDocument_NotAvailable {
            get {
                return ResourceManager.GetString("Error_OpenDocument_NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document id for opening not found.
        /// </summary>
        public static string Error_OpenDocument_NotFound {
            get {
                return ResourceManager.GetString("Error_OpenDocument_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Necessary information for opening document not provided: {0}.
        /// </summary>
        public static string Error_OpenDocument_OpenDocument_NoInformation {
            get {
                return ResourceManager.GetString("Error_OpenDocument_OpenDocument_NoInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier for open document not specified.
        /// </summary>
        public static string Error_OpenDocument_OpenDocumentId_NotSpecified {
            get {
                return ResourceManager.GetString("Error_OpenDocument_OpenDocumentId_NotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A description of the error is not available..
        /// </summary>
        public static string Error_OpenDocument_Unspecified {
            get {
                return ResourceManager.GetString("Error_OpenDocument_Unspecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t download PDF.
        /// </summary>
        public static string Error_Patent_Cant_Download_Pdf {
            get {
                return ResourceManager.GetString("Error_Patent_Cant_Download_Pdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect patent id: {0}.
        /// </summary>
        public static string Error_Patent_IncorrectPatentId {
            get {
                return ResourceManager.GetString("Error_Patent_IncorrectPatentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patent id not specified.
        /// </summary>
        public static string Error_Patent_PatentId_NotSpecified {
            get {
                return ResourceManager.GetString("Error_Patent_PatentId_NotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shape ID can&apos;t be changed: {0} -&gt; {1}.
        /// </summary>
        public static string Error_ResearchMap_ChangeShapeId {
            get {
                return ResourceManager.GetString("Error_ResearchMap_ChangeShapeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database access error.
        /// </summary>
        public static string Error_ResearchMap_DBFail {
            get {
                return ResourceManager.GetString("Error_ResearchMap_DBFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid date/time format: {0}. Accept only ISO8601.
        /// </summary>
        public static string Error_ResearchMap_InvalidDateTime_Format {
            get {
                return ResourceManager.GetString("Error_ResearchMap_InvalidDateTime_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browsed info with specified id not found: {0}.
        /// </summary>
        public static string Error_ResearchMap_NotFound_BrowsedInfo {
            get {
                return ResourceManager.GetString("Error_ResearchMap_NotFound_BrowsedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified query not found.
        /// </summary>
        public static string Error_ResearchMap_NotFound_Query {
            get {
                return ResourceManager.GetString("Error_ResearchMap_NotFound_Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested Research Guide not found: {0}.
        /// </summary>
        public static string Error_ResearchMap_NotFound_RM {
            get {
                return ResourceManager.GetString("Error_ResearchMap_NotFound_RM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shape with specified id not found: {0}.
        /// </summary>
        public static string Error_ResearchMap_NotFound_Shape {
            get {
                return ResourceManager.GetString("Error_ResearchMap_NotFound_Shape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Research guide ID should be provided in URL.
        /// </summary>
        public static string Error_ResearchMap_RMIdNotProvided {
            get {
                return ResourceManager.GetString("Error_ResearchMap_RMIdNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should be specified either kind or type, not both: {0}, {1}.
        /// </summary>
        public static string Error_ResearchMap_ShapeBothKindAndType {
            get {
                return ResourceManager.GetString("Error_ResearchMap_ShapeBothKindAndType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shape kind can&apos;t be changed..
        /// </summary>
        public static string Error_ResearchMap_ShapeCantUpdateKind {
            get {
                return ResourceManager.GetString("Error_ResearchMap_ShapeCantUpdateKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shape ID should be provided either in URL or in request body.
        /// </summary>
        public static string Error_ResearchMap_ShapeIdNotProvided {
            get {
                return ResourceManager.GetString("Error_ResearchMap_ShapeIdNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong shape kind: {0}.
        /// </summary>
        public static string Error_ResearchMap_ShapeWrongKind {
            get {
                return ResourceManager.GetString("Error_ResearchMap_ShapeWrongKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong shape type: {0}.
        /// </summary>
        public static string Error_ResearchMap_ShapeWrongType {
            get {
                return ResourceManager.GetString("Error_ResearchMap_ShapeWrongType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified shape should be node: {0}.
        /// </summary>
        public static string Error_ResearchMap_ShouldBeNode {
            get {
                return ResourceManager.GetString("Error_ResearchMap_ShouldBeNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t add node. Maximal nodes count reached..
        /// </summary>
        public static string Error_ResearchMap_ToManyNodes {
            get {
                return ResourceManager.GetString("Error_ResearchMap_ToManyNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid document id.
        /// </summary>
        public static string Error_SummaryInvalidDocId {
            get {
                return ResourceManager.GetString("Error_SummaryInvalidDocId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error from remote service.
        /// </summary>
        public static string Error_Unexpected_Remote_Error {
            get {
                return ResourceManager.GetString("Error_Unexpected_Remote_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exported file expired.
        /// </summary>
        public static string Export_TokenExpired {
            get {
                return ResourceManager.GetString("Export_TokenExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exported data.
        /// </summary>
        public static string exportDefaultFileName {
            get {
                return ResourceManager.GetString("exportDefaultFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token {0} is not found in cache..
        /// </summary>
        public static string exportErrorTokenNotFound {
            get {
                return ResourceManager.GetString("exportErrorTokenNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined request type..
        /// </summary>
        public static string exportErrorUndefinedType {
            get {
                return ResourceManager.GetString("exportErrorUndefinedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search session does not exist..
        /// </summary>
        public static string Search_SessionDoesNotExist {
            get {
                return ResourceManager.GetString("Search_SessionDoesNotExist", resourceCulture);
            }
        }
    }
}
